### ISSUE TITLE
ipyleaflet no long works in Colab

### ISSUE THREAD

**Issue by giswqs** [googlecolab/colab-cdn-widget-manager#25]
@blois It seems ipyleaflet no long works in Colab. The map does not show up. Has Colab recently changed something that breaks the widget manager?  Relevant issue: https://github.com/giswqs/geemap/issues/1132

@martinRenou @davidbrochart @jasongrout

```python
from google.colab import output
output.enable_custom_widget_manager()

import ipyleaflet
m = ipyleaflet.Map()
m
```

**Comment by jasongrout** [comment]
@blois - ipyleaflet 0.17.0 introduces a new way to get the webpack public path, so that the ipyleaflet dist/index.js will load extra assets from wherever it is originally loaded from rather than always being hardcoded to go back to unpkg. It relies on the requirejs 'module' magic dependency: https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#module

The error I'm seeing in Colab is that the loadModule function does not know how to get the 'module' dependency ("Error has occurred while trying to update output. Error: Unknown dependency module"). It looks like your loadModule function does not actually use requirejs to load modules? Can you add support for the magic 'module' dependency that exports a structure with info about where the module was loaded from? I imagine you can just hardcode a branch in the code that looks for the `'module'` dependency, and instead of trying to load something, just responds with the info as documented in the above requirejs wiki link.

The change in ipyleaflet is https://github.com/jupyter-widgets/ipyleaflet/pull/988

**Comment by jasongrout** [comment]
I'm hoping to spread that change to other custom widgets and ipywidgets 8, so it would be good to make sure it works here, or figure out another solution if this is going to cause a lot of problems.
